package com.raddle.crud.model.toolgen;

import java.util.Date;

public class CrudItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_ITEM.ID
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_ITEM.CRUD_DEF_ID
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    private Long crudDefId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_ITEM.FK_TYPE
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    private String fkType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_ITEM.TITLE
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_ITEM.VAR_NAME
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    private String varName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_ITEM.ITEM_TYPE
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    private String itemType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_ITEM.INPUT_TYPE
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    private String inputType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_ITEM.ACTION_TYPE
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    private String actionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_ITEM.HREF
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    private String href;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_ITEM.WEB_CHK_RULE
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    private String webChkRule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_ITEM.SERVER_CHK_RULE
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    private String serverChkRule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_ITEM.OPTION_TYPE
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    private String optionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_ITEM.OPTION_VALUE
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    private String optionValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_ITEM.CRUD_DS_ID
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    private Long crudDsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_ITEM.DELETED
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    private Short deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_ITEM.CREATED_AT
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_ITEM.UPDATED_AT
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_ITEM.ID
     *
     * @return the value of CRUD_ITEM.ID
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_ITEM.ID
     *
     * @param id the value for CRUD_ITEM.ID
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_ITEM.CRUD_DEF_ID
     *
     * @return the value of CRUD_ITEM.CRUD_DEF_ID
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public Long getCrudDefId() {
        return crudDefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_ITEM.CRUD_DEF_ID
     *
     * @param crudDefId the value for CRUD_ITEM.CRUD_DEF_ID
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public void setCrudDefId(Long crudDefId) {
        this.crudDefId = crudDefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_ITEM.FK_TYPE
     *
     * @return the value of CRUD_ITEM.FK_TYPE
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public String getFkType() {
        return fkType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_ITEM.FK_TYPE
     *
     * @param fkType the value for CRUD_ITEM.FK_TYPE
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public void setFkType(String fkType) {
        this.fkType = fkType == null ? null : fkType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_ITEM.TITLE
     *
     * @return the value of CRUD_ITEM.TITLE
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_ITEM.TITLE
     *
     * @param title the value for CRUD_ITEM.TITLE
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_ITEM.VAR_NAME
     *
     * @return the value of CRUD_ITEM.VAR_NAME
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public String getVarName() {
        return varName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_ITEM.VAR_NAME
     *
     * @param varName the value for CRUD_ITEM.VAR_NAME
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public void setVarName(String varName) {
        this.varName = varName == null ? null : varName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_ITEM.ITEM_TYPE
     *
     * @return the value of CRUD_ITEM.ITEM_TYPE
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public String getItemType() {
        return itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_ITEM.ITEM_TYPE
     *
     * @param itemType the value for CRUD_ITEM.ITEM_TYPE
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public void setItemType(String itemType) {
        this.itemType = itemType == null ? null : itemType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_ITEM.INPUT_TYPE
     *
     * @return the value of CRUD_ITEM.INPUT_TYPE
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public String getInputType() {
        return inputType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_ITEM.INPUT_TYPE
     *
     * @param inputType the value for CRUD_ITEM.INPUT_TYPE
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public void setInputType(String inputType) {
        this.inputType = inputType == null ? null : inputType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_ITEM.ACTION_TYPE
     *
     * @return the value of CRUD_ITEM.ACTION_TYPE
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public String getActionType() {
        return actionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_ITEM.ACTION_TYPE
     *
     * @param actionType the value for CRUD_ITEM.ACTION_TYPE
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public void setActionType(String actionType) {
        this.actionType = actionType == null ? null : actionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_ITEM.HREF
     *
     * @return the value of CRUD_ITEM.HREF
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public String getHref() {
        return href;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_ITEM.HREF
     *
     * @param href the value for CRUD_ITEM.HREF
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public void setHref(String href) {
        this.href = href == null ? null : href.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_ITEM.WEB_CHK_RULE
     *
     * @return the value of CRUD_ITEM.WEB_CHK_RULE
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public String getWebChkRule() {
        return webChkRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_ITEM.WEB_CHK_RULE
     *
     * @param webChkRule the value for CRUD_ITEM.WEB_CHK_RULE
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public void setWebChkRule(String webChkRule) {
        this.webChkRule = webChkRule == null ? null : webChkRule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_ITEM.SERVER_CHK_RULE
     *
     * @return the value of CRUD_ITEM.SERVER_CHK_RULE
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public String getServerChkRule() {
        return serverChkRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_ITEM.SERVER_CHK_RULE
     *
     * @param serverChkRule the value for CRUD_ITEM.SERVER_CHK_RULE
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public void setServerChkRule(String serverChkRule) {
        this.serverChkRule = serverChkRule == null ? null : serverChkRule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_ITEM.OPTION_TYPE
     *
     * @return the value of CRUD_ITEM.OPTION_TYPE
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public String getOptionType() {
        return optionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_ITEM.OPTION_TYPE
     *
     * @param optionType the value for CRUD_ITEM.OPTION_TYPE
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public void setOptionType(String optionType) {
        this.optionType = optionType == null ? null : optionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_ITEM.OPTION_VALUE
     *
     * @return the value of CRUD_ITEM.OPTION_VALUE
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public String getOptionValue() {
        return optionValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_ITEM.OPTION_VALUE
     *
     * @param optionValue the value for CRUD_ITEM.OPTION_VALUE
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public void setOptionValue(String optionValue) {
        this.optionValue = optionValue == null ? null : optionValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_ITEM.CRUD_DS_ID
     *
     * @return the value of CRUD_ITEM.CRUD_DS_ID
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public Long getCrudDsId() {
        return crudDsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_ITEM.CRUD_DS_ID
     *
     * @param crudDsId the value for CRUD_ITEM.CRUD_DS_ID
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public void setCrudDsId(Long crudDsId) {
        this.crudDsId = crudDsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_ITEM.DELETED
     *
     * @return the value of CRUD_ITEM.DELETED
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public Short getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_ITEM.DELETED
     *
     * @param deleted the value for CRUD_ITEM.DELETED
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public void setDeleted(Short deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_ITEM.CREATED_AT
     *
     * @return the value of CRUD_ITEM.CREATED_AT
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_ITEM.CREATED_AT
     *
     * @param createdAt the value for CRUD_ITEM.CREATED_AT
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_ITEM.UPDATED_AT
     *
     * @return the value of CRUD_ITEM.UPDATED_AT
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_ITEM.UPDATED_AT
     *
     * @param updatedAt the value for CRUD_ITEM.UPDATED_AT
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}