package com.raddle.crud.model.toolgen;

import java.util.Date;

public class CrudDatasource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_DATASOURCE.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_DATASOURCE.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_DATASOURCE.DIRVER_CLASS_NAME
     *
     * @mbggenerated
     */
    private String dirverClassName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_DATASOURCE.URL
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_DATASOURCE.USERNAME
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_DATASOURCE.PASSWORD
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_DATASOURCE.DELETED
     *
     * @mbggenerated
     */
    private Short deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_DATASOURCE.CREATED_AT
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_DATASOURCE.UPDATED_AT
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_DATASOURCE.CODE
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_DATASOURCE.ENV_CODE
     *
     * @mbggenerated
     */
    private String envCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_DATASOURCE.ID
     *
     * @return the value of CRUD_DATASOURCE.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_DATASOURCE.ID
     *
     * @param id the value for CRUD_DATASOURCE.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_DATASOURCE.NAME
     *
     * @return the value of CRUD_DATASOURCE.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_DATASOURCE.NAME
     *
     * @param name the value for CRUD_DATASOURCE.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_DATASOURCE.DIRVER_CLASS_NAME
     *
     * @return the value of CRUD_DATASOURCE.DIRVER_CLASS_NAME
     *
     * @mbggenerated
     */
    public String getDirverClassName() {
        return dirverClassName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_DATASOURCE.DIRVER_CLASS_NAME
     *
     * @param dirverClassName the value for CRUD_DATASOURCE.DIRVER_CLASS_NAME
     *
     * @mbggenerated
     */
    public void setDirverClassName(String dirverClassName) {
        this.dirverClassName = dirverClassName == null ? null : dirverClassName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_DATASOURCE.URL
     *
     * @return the value of CRUD_DATASOURCE.URL
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_DATASOURCE.URL
     *
     * @param url the value for CRUD_DATASOURCE.URL
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_DATASOURCE.USERNAME
     *
     * @return the value of CRUD_DATASOURCE.USERNAME
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_DATASOURCE.USERNAME
     *
     * @param username the value for CRUD_DATASOURCE.USERNAME
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_DATASOURCE.PASSWORD
     *
     * @return the value of CRUD_DATASOURCE.PASSWORD
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_DATASOURCE.PASSWORD
     *
     * @param password the value for CRUD_DATASOURCE.PASSWORD
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_DATASOURCE.DELETED
     *
     * @return the value of CRUD_DATASOURCE.DELETED
     *
     * @mbggenerated
     */
    public Short getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_DATASOURCE.DELETED
     *
     * @param deleted the value for CRUD_DATASOURCE.DELETED
     *
     * @mbggenerated
     */
    public void setDeleted(Short deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_DATASOURCE.CREATED_AT
     *
     * @return the value of CRUD_DATASOURCE.CREATED_AT
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_DATASOURCE.CREATED_AT
     *
     * @param createdAt the value for CRUD_DATASOURCE.CREATED_AT
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_DATASOURCE.UPDATED_AT
     *
     * @return the value of CRUD_DATASOURCE.UPDATED_AT
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_DATASOURCE.UPDATED_AT
     *
     * @param updatedAt the value for CRUD_DATASOURCE.UPDATED_AT
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_DATASOURCE.CODE
     *
     * @return the value of CRUD_DATASOURCE.CODE
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_DATASOURCE.CODE
     *
     * @param code the value for CRUD_DATASOURCE.CODE
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_DATASOURCE.ENV_CODE
     *
     * @return the value of CRUD_DATASOURCE.ENV_CODE
     *
     * @mbggenerated
     */
    public String getEnvCode() {
        return envCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_DATASOURCE.ENV_CODE
     *
     * @param envCode the value for CRUD_DATASOURCE.ENV_CODE
     *
     * @mbggenerated
     */
    public void setEnvCode(String envCode) {
        this.envCode = envCode == null ? null : envCode.trim();
    }
}