package com.raddle.crud.model.toolgen;

import java.util.Date;

public class CrudDefinition {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_DEFINITION.ID
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_DEFINITION.CODE
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_DEFINITION.NAME
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_DEFINITION.DEF_TYPE
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    private String defType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_DEFINITION.TABLE_NAME
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    private String tableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_DEFINITION.CRUD_DS_ID
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    private Long crudDsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_DEFINITION.PRE_SQL
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    private String preSql;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_DEFINITION.SQL_TYPE
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    private String sqlType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_DEFINITION.SQL
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    private String sql;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_DEFINITION.CREATE_TM_COL
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    private String createTmCol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_DEFINITION.UPDATE_TM_COL
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    private String updateTmCol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_DEFINITION.DELETED
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    private Short deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_DEFINITION.CREATED_AT
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_DEFINITION.UPDATED_AT
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_DEFINITION.ID
     *
     * @return the value of CRUD_DEFINITION.ID
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_DEFINITION.ID
     *
     * @param id the value for CRUD_DEFINITION.ID
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_DEFINITION.CODE
     *
     * @return the value of CRUD_DEFINITION.CODE
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_DEFINITION.CODE
     *
     * @param code the value for CRUD_DEFINITION.CODE
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_DEFINITION.NAME
     *
     * @return the value of CRUD_DEFINITION.NAME
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_DEFINITION.NAME
     *
     * @param name the value for CRUD_DEFINITION.NAME
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_DEFINITION.DEF_TYPE
     *
     * @return the value of CRUD_DEFINITION.DEF_TYPE
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public String getDefType() {
        return defType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_DEFINITION.DEF_TYPE
     *
     * @param defType the value for CRUD_DEFINITION.DEF_TYPE
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public void setDefType(String defType) {
        this.defType = defType == null ? null : defType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_DEFINITION.TABLE_NAME
     *
     * @return the value of CRUD_DEFINITION.TABLE_NAME
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_DEFINITION.TABLE_NAME
     *
     * @param tableName the value for CRUD_DEFINITION.TABLE_NAME
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_DEFINITION.CRUD_DS_ID
     *
     * @return the value of CRUD_DEFINITION.CRUD_DS_ID
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public Long getCrudDsId() {
        return crudDsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_DEFINITION.CRUD_DS_ID
     *
     * @param crudDsId the value for CRUD_DEFINITION.CRUD_DS_ID
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public void setCrudDsId(Long crudDsId) {
        this.crudDsId = crudDsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_DEFINITION.PRE_SQL
     *
     * @return the value of CRUD_DEFINITION.PRE_SQL
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public String getPreSql() {
        return preSql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_DEFINITION.PRE_SQL
     *
     * @param preSql the value for CRUD_DEFINITION.PRE_SQL
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public void setPreSql(String preSql) {
        this.preSql = preSql == null ? null : preSql.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_DEFINITION.SQL_TYPE
     *
     * @return the value of CRUD_DEFINITION.SQL_TYPE
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public String getSqlType() {
        return sqlType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_DEFINITION.SQL_TYPE
     *
     * @param sqlType the value for CRUD_DEFINITION.SQL_TYPE
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public void setSqlType(String sqlType) {
        this.sqlType = sqlType == null ? null : sqlType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_DEFINITION.SQL
     *
     * @return the value of CRUD_DEFINITION.SQL
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public String getSql() {
        return sql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_DEFINITION.SQL
     *
     * @param sql the value for CRUD_DEFINITION.SQL
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public void setSql(String sql) {
        this.sql = sql == null ? null : sql.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_DEFINITION.CREATE_TM_COL
     *
     * @return the value of CRUD_DEFINITION.CREATE_TM_COL
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public String getCreateTmCol() {
        return createTmCol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_DEFINITION.CREATE_TM_COL
     *
     * @param createTmCol the value for CRUD_DEFINITION.CREATE_TM_COL
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public void setCreateTmCol(String createTmCol) {
        this.createTmCol = createTmCol == null ? null : createTmCol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_DEFINITION.UPDATE_TM_COL
     *
     * @return the value of CRUD_DEFINITION.UPDATE_TM_COL
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public String getUpdateTmCol() {
        return updateTmCol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_DEFINITION.UPDATE_TM_COL
     *
     * @param updateTmCol the value for CRUD_DEFINITION.UPDATE_TM_COL
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public void setUpdateTmCol(String updateTmCol) {
        this.updateTmCol = updateTmCol == null ? null : updateTmCol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_DEFINITION.DELETED
     *
     * @return the value of CRUD_DEFINITION.DELETED
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public Short getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_DEFINITION.DELETED
     *
     * @param deleted the value for CRUD_DEFINITION.DELETED
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public void setDeleted(Short deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_DEFINITION.CREATED_AT
     *
     * @return the value of CRUD_DEFINITION.CREATED_AT
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_DEFINITION.CREATED_AT
     *
     * @param createdAt the value for CRUD_DEFINITION.CREATED_AT
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_DEFINITION.UPDATED_AT
     *
     * @return the value of CRUD_DEFINITION.UPDATED_AT
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_DEFINITION.UPDATED_AT
     *
     * @param updatedAt the value for CRUD_DEFINITION.UPDATED_AT
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}