package com.raddle.crud.model.toolgen;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CrudDefinitionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CRUD_DEFINITION
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CRUD_DEFINITION
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CRUD_DEFINITION
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRUD_DEFINITION
     *
     * @mbggenerated
     */
    public CrudDefinitionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRUD_DEFINITION
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRUD_DEFINITION
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRUD_DEFINITION
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRUD_DEFINITION
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRUD_DEFINITION
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRUD_DEFINITION
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRUD_DEFINITION
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRUD_DEFINITION
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRUD_DEFINITION
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRUD_DEFINITION
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CRUD_DEFINITION
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("NAME in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("NAME not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andDefTypeIsNull() {
            addCriterion("DEF_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andDefTypeIsNotNull() {
            addCriterion("DEF_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andDefTypeEqualTo(String value) {
            addCriterion("DEF_TYPE =", value, "defType");
            return (Criteria) this;
        }

        public Criteria andDefTypeNotEqualTo(String value) {
            addCriterion("DEF_TYPE <>", value, "defType");
            return (Criteria) this;
        }

        public Criteria andDefTypeGreaterThan(String value) {
            addCriterion("DEF_TYPE >", value, "defType");
            return (Criteria) this;
        }

        public Criteria andDefTypeGreaterThanOrEqualTo(String value) {
            addCriterion("DEF_TYPE >=", value, "defType");
            return (Criteria) this;
        }

        public Criteria andDefTypeLessThan(String value) {
            addCriterion("DEF_TYPE <", value, "defType");
            return (Criteria) this;
        }

        public Criteria andDefTypeLessThanOrEqualTo(String value) {
            addCriterion("DEF_TYPE <=", value, "defType");
            return (Criteria) this;
        }

        public Criteria andDefTypeLike(String value) {
            addCriterion("DEF_TYPE like", value, "defType");
            return (Criteria) this;
        }

        public Criteria andDefTypeNotLike(String value) {
            addCriterion("DEF_TYPE not like", value, "defType");
            return (Criteria) this;
        }

        public Criteria andDefTypeIn(List<String> values) {
            addCriterion("DEF_TYPE in", values, "defType");
            return (Criteria) this;
        }

        public Criteria andDefTypeNotIn(List<String> values) {
            addCriterion("DEF_TYPE not in", values, "defType");
            return (Criteria) this;
        }

        public Criteria andDefTypeBetween(String value1, String value2) {
            addCriterion("DEF_TYPE between", value1, value2, "defType");
            return (Criteria) this;
        }

        public Criteria andDefTypeNotBetween(String value1, String value2) {
            addCriterion("DEF_TYPE not between", value1, value2, "defType");
            return (Criteria) this;
        }

        public Criteria andTableNameIsNull() {
            addCriterion("TABLE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andTableNameIsNotNull() {
            addCriterion("TABLE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andTableNameEqualTo(String value) {
            addCriterion("TABLE_NAME =", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameNotEqualTo(String value) {
            addCriterion("TABLE_NAME <>", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameGreaterThan(String value) {
            addCriterion("TABLE_NAME >", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameGreaterThanOrEqualTo(String value) {
            addCriterion("TABLE_NAME >=", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameLessThan(String value) {
            addCriterion("TABLE_NAME <", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameLessThanOrEqualTo(String value) {
            addCriterion("TABLE_NAME <=", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameLike(String value) {
            addCriterion("TABLE_NAME like", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameNotLike(String value) {
            addCriterion("TABLE_NAME not like", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameIn(List<String> values) {
            addCriterion("TABLE_NAME in", values, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameNotIn(List<String> values) {
            addCriterion("TABLE_NAME not in", values, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameBetween(String value1, String value2) {
            addCriterion("TABLE_NAME between", value1, value2, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameNotBetween(String value1, String value2) {
            addCriterion("TABLE_NAME not between", value1, value2, "tableName");
            return (Criteria) this;
        }

        public Criteria andCrudDsIdIsNull() {
            addCriterion("CRUD_DS_ID is null");
            return (Criteria) this;
        }

        public Criteria andCrudDsIdIsNotNull() {
            addCriterion("CRUD_DS_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCrudDsIdEqualTo(Long value) {
            addCriterion("CRUD_DS_ID =", value, "crudDsId");
            return (Criteria) this;
        }

        public Criteria andCrudDsIdNotEqualTo(Long value) {
            addCriterion("CRUD_DS_ID <>", value, "crudDsId");
            return (Criteria) this;
        }

        public Criteria andCrudDsIdGreaterThan(Long value) {
            addCriterion("CRUD_DS_ID >", value, "crudDsId");
            return (Criteria) this;
        }

        public Criteria andCrudDsIdGreaterThanOrEqualTo(Long value) {
            addCriterion("CRUD_DS_ID >=", value, "crudDsId");
            return (Criteria) this;
        }

        public Criteria andCrudDsIdLessThan(Long value) {
            addCriterion("CRUD_DS_ID <", value, "crudDsId");
            return (Criteria) this;
        }

        public Criteria andCrudDsIdLessThanOrEqualTo(Long value) {
            addCriterion("CRUD_DS_ID <=", value, "crudDsId");
            return (Criteria) this;
        }

        public Criteria andCrudDsIdIn(List<Long> values) {
            addCriterion("CRUD_DS_ID in", values, "crudDsId");
            return (Criteria) this;
        }

        public Criteria andCrudDsIdNotIn(List<Long> values) {
            addCriterion("CRUD_DS_ID not in", values, "crudDsId");
            return (Criteria) this;
        }

        public Criteria andCrudDsIdBetween(Long value1, Long value2) {
            addCriterion("CRUD_DS_ID between", value1, value2, "crudDsId");
            return (Criteria) this;
        }

        public Criteria andCrudDsIdNotBetween(Long value1, Long value2) {
            addCriterion("CRUD_DS_ID not between", value1, value2, "crudDsId");
            return (Criteria) this;
        }

        public Criteria andPreSqlIsNull() {
            addCriterion("PRE_SQL is null");
            return (Criteria) this;
        }

        public Criteria andPreSqlIsNotNull() {
            addCriterion("PRE_SQL is not null");
            return (Criteria) this;
        }

        public Criteria andPreSqlEqualTo(String value) {
            addCriterion("PRE_SQL =", value, "preSql");
            return (Criteria) this;
        }

        public Criteria andPreSqlNotEqualTo(String value) {
            addCriterion("PRE_SQL <>", value, "preSql");
            return (Criteria) this;
        }

        public Criteria andPreSqlGreaterThan(String value) {
            addCriterion("PRE_SQL >", value, "preSql");
            return (Criteria) this;
        }

        public Criteria andPreSqlGreaterThanOrEqualTo(String value) {
            addCriterion("PRE_SQL >=", value, "preSql");
            return (Criteria) this;
        }

        public Criteria andPreSqlLessThan(String value) {
            addCriterion("PRE_SQL <", value, "preSql");
            return (Criteria) this;
        }

        public Criteria andPreSqlLessThanOrEqualTo(String value) {
            addCriterion("PRE_SQL <=", value, "preSql");
            return (Criteria) this;
        }

        public Criteria andPreSqlLike(String value) {
            addCriterion("PRE_SQL like", value, "preSql");
            return (Criteria) this;
        }

        public Criteria andPreSqlNotLike(String value) {
            addCriterion("PRE_SQL not like", value, "preSql");
            return (Criteria) this;
        }

        public Criteria andPreSqlIn(List<String> values) {
            addCriterion("PRE_SQL in", values, "preSql");
            return (Criteria) this;
        }

        public Criteria andPreSqlNotIn(List<String> values) {
            addCriterion("PRE_SQL not in", values, "preSql");
            return (Criteria) this;
        }

        public Criteria andPreSqlBetween(String value1, String value2) {
            addCriterion("PRE_SQL between", value1, value2, "preSql");
            return (Criteria) this;
        }

        public Criteria andPreSqlNotBetween(String value1, String value2) {
            addCriterion("PRE_SQL not between", value1, value2, "preSql");
            return (Criteria) this;
        }

        public Criteria andReadSqlIsNull() {
            addCriterion("READ_SQL is null");
            return (Criteria) this;
        }

        public Criteria andReadSqlIsNotNull() {
            addCriterion("READ_SQL is not null");
            return (Criteria) this;
        }

        public Criteria andReadSqlEqualTo(String value) {
            addCriterion("READ_SQL =", value, "readSql");
            return (Criteria) this;
        }

        public Criteria andReadSqlNotEqualTo(String value) {
            addCriterion("READ_SQL <>", value, "readSql");
            return (Criteria) this;
        }

        public Criteria andReadSqlGreaterThan(String value) {
            addCriterion("READ_SQL >", value, "readSql");
            return (Criteria) this;
        }

        public Criteria andReadSqlGreaterThanOrEqualTo(String value) {
            addCriterion("READ_SQL >=", value, "readSql");
            return (Criteria) this;
        }

        public Criteria andReadSqlLessThan(String value) {
            addCriterion("READ_SQL <", value, "readSql");
            return (Criteria) this;
        }

        public Criteria andReadSqlLessThanOrEqualTo(String value) {
            addCriterion("READ_SQL <=", value, "readSql");
            return (Criteria) this;
        }

        public Criteria andReadSqlLike(String value) {
            addCriterion("READ_SQL like", value, "readSql");
            return (Criteria) this;
        }

        public Criteria andReadSqlNotLike(String value) {
            addCriterion("READ_SQL not like", value, "readSql");
            return (Criteria) this;
        }

        public Criteria andReadSqlIn(List<String> values) {
            addCriterion("READ_SQL in", values, "readSql");
            return (Criteria) this;
        }

        public Criteria andReadSqlNotIn(List<String> values) {
            addCriterion("READ_SQL not in", values, "readSql");
            return (Criteria) this;
        }

        public Criteria andReadSqlBetween(String value1, String value2) {
            addCriterion("READ_SQL between", value1, value2, "readSql");
            return (Criteria) this;
        }

        public Criteria andReadSqlNotBetween(String value1, String value2) {
            addCriterion("READ_SQL not between", value1, value2, "readSql");
            return (Criteria) this;
        }

        public Criteria andKeySelectSqlIsNull() {
            addCriterion("KEY_SELECT_SQL is null");
            return (Criteria) this;
        }

        public Criteria andKeySelectSqlIsNotNull() {
            addCriterion("KEY_SELECT_SQL is not null");
            return (Criteria) this;
        }

        public Criteria andKeySelectSqlEqualTo(String value) {
            addCriterion("KEY_SELECT_SQL =", value, "keySelectSql");
            return (Criteria) this;
        }

        public Criteria andKeySelectSqlNotEqualTo(String value) {
            addCriterion("KEY_SELECT_SQL <>", value, "keySelectSql");
            return (Criteria) this;
        }

        public Criteria andKeySelectSqlGreaterThan(String value) {
            addCriterion("KEY_SELECT_SQL >", value, "keySelectSql");
            return (Criteria) this;
        }

        public Criteria andKeySelectSqlGreaterThanOrEqualTo(String value) {
            addCriterion("KEY_SELECT_SQL >=", value, "keySelectSql");
            return (Criteria) this;
        }

        public Criteria andKeySelectSqlLessThan(String value) {
            addCriterion("KEY_SELECT_SQL <", value, "keySelectSql");
            return (Criteria) this;
        }

        public Criteria andKeySelectSqlLessThanOrEqualTo(String value) {
            addCriterion("KEY_SELECT_SQL <=", value, "keySelectSql");
            return (Criteria) this;
        }

        public Criteria andKeySelectSqlLike(String value) {
            addCriterion("KEY_SELECT_SQL like", value, "keySelectSql");
            return (Criteria) this;
        }

        public Criteria andKeySelectSqlNotLike(String value) {
            addCriterion("KEY_SELECT_SQL not like", value, "keySelectSql");
            return (Criteria) this;
        }

        public Criteria andKeySelectSqlIn(List<String> values) {
            addCriterion("KEY_SELECT_SQL in", values, "keySelectSql");
            return (Criteria) this;
        }

        public Criteria andKeySelectSqlNotIn(List<String> values) {
            addCriterion("KEY_SELECT_SQL not in", values, "keySelectSql");
            return (Criteria) this;
        }

        public Criteria andKeySelectSqlBetween(String value1, String value2) {
            addCriterion("KEY_SELECT_SQL between", value1, value2, "keySelectSql");
            return (Criteria) this;
        }

        public Criteria andKeySelectSqlNotBetween(String value1, String value2) {
            addCriterion("KEY_SELECT_SQL not between", value1, value2, "keySelectSql");
            return (Criteria) this;
        }

        public Criteria andUpdateSqlIsNull() {
            addCriterion("UPDATE_SQL is null");
            return (Criteria) this;
        }

        public Criteria andUpdateSqlIsNotNull() {
            addCriterion("UPDATE_SQL is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateSqlEqualTo(String value) {
            addCriterion("UPDATE_SQL =", value, "updateSql");
            return (Criteria) this;
        }

        public Criteria andUpdateSqlNotEqualTo(String value) {
            addCriterion("UPDATE_SQL <>", value, "updateSql");
            return (Criteria) this;
        }

        public Criteria andUpdateSqlGreaterThan(String value) {
            addCriterion("UPDATE_SQL >", value, "updateSql");
            return (Criteria) this;
        }

        public Criteria andUpdateSqlGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_SQL >=", value, "updateSql");
            return (Criteria) this;
        }

        public Criteria andUpdateSqlLessThan(String value) {
            addCriterion("UPDATE_SQL <", value, "updateSql");
            return (Criteria) this;
        }

        public Criteria andUpdateSqlLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_SQL <=", value, "updateSql");
            return (Criteria) this;
        }

        public Criteria andUpdateSqlLike(String value) {
            addCriterion("UPDATE_SQL like", value, "updateSql");
            return (Criteria) this;
        }

        public Criteria andUpdateSqlNotLike(String value) {
            addCriterion("UPDATE_SQL not like", value, "updateSql");
            return (Criteria) this;
        }

        public Criteria andUpdateSqlIn(List<String> values) {
            addCriterion("UPDATE_SQL in", values, "updateSql");
            return (Criteria) this;
        }

        public Criteria andUpdateSqlNotIn(List<String> values) {
            addCriterion("UPDATE_SQL not in", values, "updateSql");
            return (Criteria) this;
        }

        public Criteria andUpdateSqlBetween(String value1, String value2) {
            addCriterion("UPDATE_SQL between", value1, value2, "updateSql");
            return (Criteria) this;
        }

        public Criteria andUpdateSqlNotBetween(String value1, String value2) {
            addCriterion("UPDATE_SQL not between", value1, value2, "updateSql");
            return (Criteria) this;
        }

        public Criteria andAddHrefIsNull() {
            addCriterion("ADD_HREF is null");
            return (Criteria) this;
        }

        public Criteria andAddHrefIsNotNull() {
            addCriterion("ADD_HREF is not null");
            return (Criteria) this;
        }

        public Criteria andAddHrefEqualTo(String value) {
            addCriterion("ADD_HREF =", value, "addHref");
            return (Criteria) this;
        }

        public Criteria andAddHrefNotEqualTo(String value) {
            addCriterion("ADD_HREF <>", value, "addHref");
            return (Criteria) this;
        }

        public Criteria andAddHrefGreaterThan(String value) {
            addCriterion("ADD_HREF >", value, "addHref");
            return (Criteria) this;
        }

        public Criteria andAddHrefGreaterThanOrEqualTo(String value) {
            addCriterion("ADD_HREF >=", value, "addHref");
            return (Criteria) this;
        }

        public Criteria andAddHrefLessThan(String value) {
            addCriterion("ADD_HREF <", value, "addHref");
            return (Criteria) this;
        }

        public Criteria andAddHrefLessThanOrEqualTo(String value) {
            addCriterion("ADD_HREF <=", value, "addHref");
            return (Criteria) this;
        }

        public Criteria andAddHrefLike(String value) {
            addCriterion("ADD_HREF like", value, "addHref");
            return (Criteria) this;
        }

        public Criteria andAddHrefNotLike(String value) {
            addCriterion("ADD_HREF not like", value, "addHref");
            return (Criteria) this;
        }

        public Criteria andAddHrefIn(List<String> values) {
            addCriterion("ADD_HREF in", values, "addHref");
            return (Criteria) this;
        }

        public Criteria andAddHrefNotIn(List<String> values) {
            addCriterion("ADD_HREF not in", values, "addHref");
            return (Criteria) this;
        }

        public Criteria andAddHrefBetween(String value1, String value2) {
            addCriterion("ADD_HREF between", value1, value2, "addHref");
            return (Criteria) this;
        }

        public Criteria andAddHrefNotBetween(String value1, String value2) {
            addCriterion("ADD_HREF not between", value1, value2, "addHref");
            return (Criteria) this;
        }

        public Criteria andIsPagingIsNull() {
            addCriterion("IS_PAGING is null");
            return (Criteria) this;
        }

        public Criteria andIsPagingIsNotNull() {
            addCriterion("IS_PAGING is not null");
            return (Criteria) this;
        }

        public Criteria andIsPagingEqualTo(Short value) {
            addCriterion("IS_PAGING =", value, "isPaging");
            return (Criteria) this;
        }

        public Criteria andIsPagingNotEqualTo(Short value) {
            addCriterion("IS_PAGING <>", value, "isPaging");
            return (Criteria) this;
        }

        public Criteria andIsPagingGreaterThan(Short value) {
            addCriterion("IS_PAGING >", value, "isPaging");
            return (Criteria) this;
        }

        public Criteria andIsPagingGreaterThanOrEqualTo(Short value) {
            addCriterion("IS_PAGING >=", value, "isPaging");
            return (Criteria) this;
        }

        public Criteria andIsPagingLessThan(Short value) {
            addCriterion("IS_PAGING <", value, "isPaging");
            return (Criteria) this;
        }

        public Criteria andIsPagingLessThanOrEqualTo(Short value) {
            addCriterion("IS_PAGING <=", value, "isPaging");
            return (Criteria) this;
        }

        public Criteria andIsPagingIn(List<Short> values) {
            addCriterion("IS_PAGING in", values, "isPaging");
            return (Criteria) this;
        }

        public Criteria andIsPagingNotIn(List<Short> values) {
            addCriterion("IS_PAGING not in", values, "isPaging");
            return (Criteria) this;
        }

        public Criteria andIsPagingBetween(Short value1, Short value2) {
            addCriterion("IS_PAGING between", value1, value2, "isPaging");
            return (Criteria) this;
        }

        public Criteria andIsPagingNotBetween(Short value1, Short value2) {
            addCriterion("IS_PAGING not between", value1, value2, "isPaging");
            return (Criteria) this;
        }

        public Criteria andAutoMatchBtnIsNull() {
            addCriterion("AUTO_MATCH_BTN is null");
            return (Criteria) this;
        }

        public Criteria andAutoMatchBtnIsNotNull() {
            addCriterion("AUTO_MATCH_BTN is not null");
            return (Criteria) this;
        }

        public Criteria andAutoMatchBtnEqualTo(Short value) {
            addCriterion("AUTO_MATCH_BTN =", value, "autoMatchBtn");
            return (Criteria) this;
        }

        public Criteria andAutoMatchBtnNotEqualTo(Short value) {
            addCriterion("AUTO_MATCH_BTN <>", value, "autoMatchBtn");
            return (Criteria) this;
        }

        public Criteria andAutoMatchBtnGreaterThan(Short value) {
            addCriterion("AUTO_MATCH_BTN >", value, "autoMatchBtn");
            return (Criteria) this;
        }

        public Criteria andAutoMatchBtnGreaterThanOrEqualTo(Short value) {
            addCriterion("AUTO_MATCH_BTN >=", value, "autoMatchBtn");
            return (Criteria) this;
        }

        public Criteria andAutoMatchBtnLessThan(Short value) {
            addCriterion("AUTO_MATCH_BTN <", value, "autoMatchBtn");
            return (Criteria) this;
        }

        public Criteria andAutoMatchBtnLessThanOrEqualTo(Short value) {
            addCriterion("AUTO_MATCH_BTN <=", value, "autoMatchBtn");
            return (Criteria) this;
        }

        public Criteria andAutoMatchBtnIn(List<Short> values) {
            addCriterion("AUTO_MATCH_BTN in", values, "autoMatchBtn");
            return (Criteria) this;
        }

        public Criteria andAutoMatchBtnNotIn(List<Short> values) {
            addCriterion("AUTO_MATCH_BTN not in", values, "autoMatchBtn");
            return (Criteria) this;
        }

        public Criteria andAutoMatchBtnBetween(Short value1, Short value2) {
            addCriterion("AUTO_MATCH_BTN between", value1, value2, "autoMatchBtn");
            return (Criteria) this;
        }

        public Criteria andAutoMatchBtnNotBetween(Short value1, Short value2) {
            addCriterion("AUTO_MATCH_BTN not between", value1, value2, "autoMatchBtn");
            return (Criteria) this;
        }

        public Criteria andCreateTmColIsNull() {
            addCriterion("CREATE_TM_COL is null");
            return (Criteria) this;
        }

        public Criteria andCreateTmColIsNotNull() {
            addCriterion("CREATE_TM_COL is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTmColEqualTo(String value) {
            addCriterion("CREATE_TM_COL =", value, "createTmCol");
            return (Criteria) this;
        }

        public Criteria andCreateTmColNotEqualTo(String value) {
            addCriterion("CREATE_TM_COL <>", value, "createTmCol");
            return (Criteria) this;
        }

        public Criteria andCreateTmColGreaterThan(String value) {
            addCriterion("CREATE_TM_COL >", value, "createTmCol");
            return (Criteria) this;
        }

        public Criteria andCreateTmColGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_TM_COL >=", value, "createTmCol");
            return (Criteria) this;
        }

        public Criteria andCreateTmColLessThan(String value) {
            addCriterion("CREATE_TM_COL <", value, "createTmCol");
            return (Criteria) this;
        }

        public Criteria andCreateTmColLessThanOrEqualTo(String value) {
            addCriterion("CREATE_TM_COL <=", value, "createTmCol");
            return (Criteria) this;
        }

        public Criteria andCreateTmColLike(String value) {
            addCriterion("CREATE_TM_COL like", value, "createTmCol");
            return (Criteria) this;
        }

        public Criteria andCreateTmColNotLike(String value) {
            addCriterion("CREATE_TM_COL not like", value, "createTmCol");
            return (Criteria) this;
        }

        public Criteria andCreateTmColIn(List<String> values) {
            addCriterion("CREATE_TM_COL in", values, "createTmCol");
            return (Criteria) this;
        }

        public Criteria andCreateTmColNotIn(List<String> values) {
            addCriterion("CREATE_TM_COL not in", values, "createTmCol");
            return (Criteria) this;
        }

        public Criteria andCreateTmColBetween(String value1, String value2) {
            addCriterion("CREATE_TM_COL between", value1, value2, "createTmCol");
            return (Criteria) this;
        }

        public Criteria andCreateTmColNotBetween(String value1, String value2) {
            addCriterion("CREATE_TM_COL not between", value1, value2, "createTmCol");
            return (Criteria) this;
        }

        public Criteria andUpdateTmColIsNull() {
            addCriterion("UPDATE_TM_COL is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTmColIsNotNull() {
            addCriterion("UPDATE_TM_COL is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTmColEqualTo(String value) {
            addCriterion("UPDATE_TM_COL =", value, "updateTmCol");
            return (Criteria) this;
        }

        public Criteria andUpdateTmColNotEqualTo(String value) {
            addCriterion("UPDATE_TM_COL <>", value, "updateTmCol");
            return (Criteria) this;
        }

        public Criteria andUpdateTmColGreaterThan(String value) {
            addCriterion("UPDATE_TM_COL >", value, "updateTmCol");
            return (Criteria) this;
        }

        public Criteria andUpdateTmColGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_TM_COL >=", value, "updateTmCol");
            return (Criteria) this;
        }

        public Criteria andUpdateTmColLessThan(String value) {
            addCriterion("UPDATE_TM_COL <", value, "updateTmCol");
            return (Criteria) this;
        }

        public Criteria andUpdateTmColLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_TM_COL <=", value, "updateTmCol");
            return (Criteria) this;
        }

        public Criteria andUpdateTmColLike(String value) {
            addCriterion("UPDATE_TM_COL like", value, "updateTmCol");
            return (Criteria) this;
        }

        public Criteria andUpdateTmColNotLike(String value) {
            addCriterion("UPDATE_TM_COL not like", value, "updateTmCol");
            return (Criteria) this;
        }

        public Criteria andUpdateTmColIn(List<String> values) {
            addCriterion("UPDATE_TM_COL in", values, "updateTmCol");
            return (Criteria) this;
        }

        public Criteria andUpdateTmColNotIn(List<String> values) {
            addCriterion("UPDATE_TM_COL not in", values, "updateTmCol");
            return (Criteria) this;
        }

        public Criteria andUpdateTmColBetween(String value1, String value2) {
            addCriterion("UPDATE_TM_COL between", value1, value2, "updateTmCol");
            return (Criteria) this;
        }

        public Criteria andUpdateTmColNotBetween(String value1, String value2) {
            addCriterion("UPDATE_TM_COL not between", value1, value2, "updateTmCol");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("DELETED is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("DELETED is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Short value) {
            addCriterion("DELETED =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Short value) {
            addCriterion("DELETED <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Short value) {
            addCriterion("DELETED >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Short value) {
            addCriterion("DELETED >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Short value) {
            addCriterion("DELETED <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Short value) {
            addCriterion("DELETED <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Short> values) {
            addCriterion("DELETED in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Short> values) {
            addCriterion("DELETED not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Short value1, Short value2) {
            addCriterion("DELETED between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Short value1, Short value2) {
            addCriterion("DELETED not between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("CREATED_AT is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("CREATED_AT is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(Date value) {
            addCriterion("CREATED_AT =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(Date value) {
            addCriterion("CREATED_AT <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(Date value) {
            addCriterion("CREATED_AT >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATED_AT >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(Date value) {
            addCriterion("CREATED_AT <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
            addCriterion("CREATED_AT <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<Date> values) {
            addCriterion("CREATED_AT in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<Date> values) {
            addCriterion("CREATED_AT not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(Date value1, Date value2) {
            addCriterion("CREATED_AT between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
            addCriterion("CREATED_AT not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNull() {
            addCriterion("UPDATED_AT is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNotNull() {
            addCriterion("UPDATED_AT is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtEqualTo(Date value) {
            addCriterion("UPDATED_AT =", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotEqualTo(Date value) {
            addCriterion("UPDATED_AT <>", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThan(Date value) {
            addCriterion("UPDATED_AT >", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATED_AT >=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThan(Date value) {
            addCriterion("UPDATED_AT <", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
            addCriterion("UPDATED_AT <=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIn(List<Date> values) {
            addCriterion("UPDATED_AT in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotIn(List<Date> values) {
            addCriterion("UPDATED_AT not in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtBetween(Date value1, Date value2) {
            addCriterion("UPDATED_AT between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
            addCriterion("UPDATED_AT not between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andCompositeTemplateIsNull() {
            addCriterion("COMPOSITE_TEMPLATE is null");
            return (Criteria) this;
        }

        public Criteria andCompositeTemplateIsNotNull() {
            addCriterion("COMPOSITE_TEMPLATE is not null");
            return (Criteria) this;
        }

        public Criteria andCompositeTemplateEqualTo(String value) {
            addCriterion("COMPOSITE_TEMPLATE =", value, "compositeTemplate");
            return (Criteria) this;
        }

        public Criteria andCompositeTemplateNotEqualTo(String value) {
            addCriterion("COMPOSITE_TEMPLATE <>", value, "compositeTemplate");
            return (Criteria) this;
        }

        public Criteria andCompositeTemplateGreaterThan(String value) {
            addCriterion("COMPOSITE_TEMPLATE >", value, "compositeTemplate");
            return (Criteria) this;
        }

        public Criteria andCompositeTemplateGreaterThanOrEqualTo(String value) {
            addCriterion("COMPOSITE_TEMPLATE >=", value, "compositeTemplate");
            return (Criteria) this;
        }

        public Criteria andCompositeTemplateLessThan(String value) {
            addCriterion("COMPOSITE_TEMPLATE <", value, "compositeTemplate");
            return (Criteria) this;
        }

        public Criteria andCompositeTemplateLessThanOrEqualTo(String value) {
            addCriterion("COMPOSITE_TEMPLATE <=", value, "compositeTemplate");
            return (Criteria) this;
        }

        public Criteria andCompositeTemplateLike(String value) {
            addCriterion("COMPOSITE_TEMPLATE like", value, "compositeTemplate");
            return (Criteria) this;
        }

        public Criteria andCompositeTemplateNotLike(String value) {
            addCriterion("COMPOSITE_TEMPLATE not like", value, "compositeTemplate");
            return (Criteria) this;
        }

        public Criteria andCompositeTemplateIn(List<String> values) {
            addCriterion("COMPOSITE_TEMPLATE in", values, "compositeTemplate");
            return (Criteria) this;
        }

        public Criteria andCompositeTemplateNotIn(List<String> values) {
            addCriterion("COMPOSITE_TEMPLATE not in", values, "compositeTemplate");
            return (Criteria) this;
        }

        public Criteria andCompositeTemplateBetween(String value1, String value2) {
            addCriterion("COMPOSITE_TEMPLATE between", value1, value2, "compositeTemplate");
            return (Criteria) this;
        }

        public Criteria andCompositeTemplateNotBetween(String value1, String value2) {
            addCriterion("COMPOSITE_TEMPLATE not between", value1, value2, "compositeTemplate");
            return (Criteria) this;
        }

        public Criteria andTableSchemaIsNull() {
            addCriterion("TABLE_SCHEMA is null");
            return (Criteria) this;
        }

        public Criteria andTableSchemaIsNotNull() {
            addCriterion("TABLE_SCHEMA is not null");
            return (Criteria) this;
        }

        public Criteria andTableSchemaEqualTo(String value) {
            addCriterion("TABLE_SCHEMA =", value, "tableSchema");
            return (Criteria) this;
        }

        public Criteria andTableSchemaNotEqualTo(String value) {
            addCriterion("TABLE_SCHEMA <>", value, "tableSchema");
            return (Criteria) this;
        }

        public Criteria andTableSchemaGreaterThan(String value) {
            addCriterion("TABLE_SCHEMA >", value, "tableSchema");
            return (Criteria) this;
        }

        public Criteria andTableSchemaGreaterThanOrEqualTo(String value) {
            addCriterion("TABLE_SCHEMA >=", value, "tableSchema");
            return (Criteria) this;
        }

        public Criteria andTableSchemaLessThan(String value) {
            addCriterion("TABLE_SCHEMA <", value, "tableSchema");
            return (Criteria) this;
        }

        public Criteria andTableSchemaLessThanOrEqualTo(String value) {
            addCriterion("TABLE_SCHEMA <=", value, "tableSchema");
            return (Criteria) this;
        }

        public Criteria andTableSchemaLike(String value) {
            addCriterion("TABLE_SCHEMA like", value, "tableSchema");
            return (Criteria) this;
        }

        public Criteria andTableSchemaNotLike(String value) {
            addCriterion("TABLE_SCHEMA not like", value, "tableSchema");
            return (Criteria) this;
        }

        public Criteria andTableSchemaIn(List<String> values) {
            addCriterion("TABLE_SCHEMA in", values, "tableSchema");
            return (Criteria) this;
        }

        public Criteria andTableSchemaNotIn(List<String> values) {
            addCriterion("TABLE_SCHEMA not in", values, "tableSchema");
            return (Criteria) this;
        }

        public Criteria andTableSchemaBetween(String value1, String value2) {
            addCriterion("TABLE_SCHEMA between", value1, value2, "tableSchema");
            return (Criteria) this;
        }

        public Criteria andTableSchemaNotBetween(String value1, String value2) {
            addCriterion("TABLE_SCHEMA not between", value1, value2, "tableSchema");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CRUD_DEFINITION
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CRUD_DEFINITION
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}