package com.raddle.crud.model.toolgen;

import java.util.Date;

public class CrudDatasource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_DATASOURCE.ID
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_DATASOURCE.DIRVER_CLASS_NAME
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    private String dirverClassName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_DATASOURCE.URL
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_DATASOURCE.USERNAME
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_DATASOURCE.PASSWORD
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_DATASOURCE.DELETED
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    private Short deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_DATASOURCE.CREATED_AT
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRUD_DATASOURCE.UPDATED_AT
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_DATASOURCE.ID
     *
     * @return the value of CRUD_DATASOURCE.ID
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_DATASOURCE.ID
     *
     * @param id the value for CRUD_DATASOURCE.ID
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_DATASOURCE.DIRVER_CLASS_NAME
     *
     * @return the value of CRUD_DATASOURCE.DIRVER_CLASS_NAME
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public String getDirverClassName() {
        return dirverClassName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_DATASOURCE.DIRVER_CLASS_NAME
     *
     * @param dirverClassName the value for CRUD_DATASOURCE.DIRVER_CLASS_NAME
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public void setDirverClassName(String dirverClassName) {
        this.dirverClassName = dirverClassName == null ? null : dirverClassName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_DATASOURCE.URL
     *
     * @return the value of CRUD_DATASOURCE.URL
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_DATASOURCE.URL
     *
     * @param url the value for CRUD_DATASOURCE.URL
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_DATASOURCE.USERNAME
     *
     * @return the value of CRUD_DATASOURCE.USERNAME
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_DATASOURCE.USERNAME
     *
     * @param username the value for CRUD_DATASOURCE.USERNAME
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_DATASOURCE.PASSWORD
     *
     * @return the value of CRUD_DATASOURCE.PASSWORD
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_DATASOURCE.PASSWORD
     *
     * @param password the value for CRUD_DATASOURCE.PASSWORD
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_DATASOURCE.DELETED
     *
     * @return the value of CRUD_DATASOURCE.DELETED
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public Short getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_DATASOURCE.DELETED
     *
     * @param deleted the value for CRUD_DATASOURCE.DELETED
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public void setDeleted(Short deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_DATASOURCE.CREATED_AT
     *
     * @return the value of CRUD_DATASOURCE.CREATED_AT
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_DATASOURCE.CREATED_AT
     *
     * @param createdAt the value for CRUD_DATASOURCE.CREATED_AT
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRUD_DATASOURCE.UPDATED_AT
     *
     * @return the value of CRUD_DATASOURCE.UPDATED_AT
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRUD_DATASOURCE.UPDATED_AT
     *
     * @param updatedAt the value for CRUD_DATASOURCE.UPDATED_AT
     *
     * @mbggenerated Sun Mar 03 13:35:28 CST 2013
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}