package com.raddle.crud.dao.toolgen;

import com.raddle.crud.model.toolgen.CrudDatasource;
import com.raddle.crud.model.toolgen.CrudDatasourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface CrudDatasourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRUD_DATASOURCE
     *
     * @mbggenerated Sun Mar 03 00:00:21 CST 2013
     */
    int countByExample(CrudDatasourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRUD_DATASOURCE
     *
     * @mbggenerated Sun Mar 03 00:00:21 CST 2013
     */
    int deleteByExample(CrudDatasourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRUD_DATASOURCE
     *
     * @mbggenerated Sun Mar 03 00:00:21 CST 2013
     */
    @Delete({
        "delete from CRUD_DATASOURCE",
        "where ID = #{id,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRUD_DATASOURCE
     *
     * @mbggenerated Sun Mar 03 00:00:21 CST 2013
     */
    @Insert({
        "insert into CRUD_DATASOURCE (ID, DIRVER_CLASS_NAME, ",
        "URL, USERNAME, PASSWORD, ",
        "DELETED, CREATED_AT, ",
        "UPDATED_AT)",
        "values (#{id,jdbcType=DECIMAL}, #{dirverClassName,jdbcType=VARCHAR}, ",
        "#{url,jdbcType=VARCHAR}, #{username,jdbcType=VARCHAR}, #{password,jdbcType=VARCHAR}, ",
        "#{deleted,jdbcType=DECIMAL}, #{createdAt,jdbcType=DATE}, ",
        "#{updatedAt,jdbcType=DATE})"
    })
    int insert(CrudDatasource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRUD_DATASOURCE
     *
     * @mbggenerated Sun Mar 03 00:00:21 CST 2013
     */
    int insertSelective(CrudDatasource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRUD_DATASOURCE
     *
     * @mbggenerated Sun Mar 03 00:00:21 CST 2013
     */
    List<CrudDatasource> selectByExample(CrudDatasourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRUD_DATASOURCE
     *
     * @mbggenerated Sun Mar 03 00:00:21 CST 2013
     */
    @Select({
        "select",
        "ID, DIRVER_CLASS_NAME, URL, USERNAME, PASSWORD, DELETED, CREATED_AT, UPDATED_AT",
        "from CRUD_DATASOURCE",
        "where ID = #{id,jdbcType=DECIMAL}"
    })
    @ResultMap("BaseResultMap")
    CrudDatasource selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRUD_DATASOURCE
     *
     * @mbggenerated Sun Mar 03 00:00:21 CST 2013
     */
    int updateByExampleSelective(@Param("record") CrudDatasource record, @Param("example") CrudDatasourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRUD_DATASOURCE
     *
     * @mbggenerated Sun Mar 03 00:00:21 CST 2013
     */
    int updateByExample(@Param("record") CrudDatasource record, @Param("example") CrudDatasourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRUD_DATASOURCE
     *
     * @mbggenerated Sun Mar 03 00:00:21 CST 2013
     */
    int updateByPrimaryKeySelective(CrudDatasource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRUD_DATASOURCE
     *
     * @mbggenerated Sun Mar 03 00:00:21 CST 2013
     */
    @Update({
        "update CRUD_DATASOURCE",
        "set DIRVER_CLASS_NAME = #{dirverClassName,jdbcType=VARCHAR},",
          "URL = #{url,jdbcType=VARCHAR},",
          "USERNAME = #{username,jdbcType=VARCHAR},",
          "PASSWORD = #{password,jdbcType=VARCHAR},",
          "DELETED = #{deleted,jdbcType=DECIMAL},",
          "CREATED_AT = #{createdAt,jdbcType=DATE},",
          "UPDATED_AT = #{updatedAt,jdbcType=DATE}",
        "where ID = #{id,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(CrudDatasource record);
}